const plurals: Record<string, string> = {
  "m[ae]n$": "men",
  eaux$: "$&",
  "(child)(?:ren)?$": "$1ren",
  "(pe)(?:rson|ople)$": "$1ople",
  "\\b((?:tit)?m|l)(?:ice|ouse)$": "$1ice",
  "(matr|cod|mur|sil|vert|ind|append)(?:ix|ex)$": "$1ices",
  "(x|ch|ss|sh|zz)$": "$1es",
  "([^ch][ieo][ln])ey$": "$1ies",
  "([^aeiouy]|qu)y$": "$1ies",
  "(?:(kni|wi|li)fe|(ar|l|ea|eo|oa|hoo)f)$": "$1$2ves",
  sis$: "ses",
  "(apheli|hyperbat|periheli|asyndet|noumen|phenomen|criteri|organ|prolegomen|hedr|automat)(?:a|on)$":
    "$1a",
  "(agend|addend|millenni|dat|extrem|bacteri|desiderat|strat|candelabr|errat|ov|symposi|curricul|automat|quor)(?:a|um)$":
    "$1a",
  "(her|at|gr)o$": "$1oes",
  "(seraph|cherub)(?:im)?$": "$1im",
  "(alumn|alg|vertebr)(?:a|ae)$": "$1ae",
  "(alumn|syllab|vir|radi|nucle|fung|cact|stimul|termin|bacill|foc|uter|loc|strat)(?:us|i)$":
    "$1i",
  "([^l]ias|[aeiou]las|[ejzr]as|[iu]am)$": "$1",
  "(e[mn]u)s?$": "$1s",
  "(alias|[^aou]us|t[lm]as|gas|ris)$": "$1es",
  "(ax|test)is$": "$1es",
  "([^aeiou]ese)$": "$1",
  "[^\\u0000-\\u007F]$": "$&",
  "s?$": "s",
};

const singulars: Record<string, string> = {
  men$: "man",
  "(eau)x?$": "$1",
  "(child)ren$": "$1",
  "(pe)(rson|ople)$": "$1rson",
  "(matr|append)ices$": "$1ix",
  "(cod|mur|sil|vert|ind)ices$": "$1ex",
  "(alumn|alg|vertebr)ae$": "$1a",
  "(apheli|hyperbat|periheli|asyndet|noumen|phenomen|criteri|organ|prolegomen|hedr|automat)a$":
    "$1on",
  "(agend|addend|millenni|dat|extrem|bacteri|desiderat|strat|candelabr|errat|ov|symposi|curricul|quor)a$":
    "$1um",
  "(alumn|syllab|vir|radi|nucle|fung|cact|stimul|termin|bacill|foc|uter|loc|strat)(?:us|i)$":
    "$1us",
  "(test)(?:is|es)$": "$1is",
  "(movie|twelve|abuse|e[mn]u)s$": "$1",
  "(analy|diagno|parenthe|progno|synop|the|empha|cri|ne)(?:sis|ses)$": "$1sis",
  "(x|ch|ss|sh|zz|tto|go|cho|alias|[^aou]us|t[lm]as|gas|(?:her|at|gr)o|[aeiou]ris)(?:es)?$":
    "$1",
  "(seraph|cherub)im$": "$1",
  "\\b((?:tit)?m|l)ice$": "$1ouse",
  "\\b(mon|smil)ies$": "$1ey",
  "\\b(l|(?:neck|cross|hog|aun)?t|coll|faer|food|gen|goon|group|hipp|junk|vegg|(?:pork)?p|charl|calor|cut)ies$":
    "$1ie",
  "(dg|ss|ois|lk|ok|wn|mb|th|ch|ec|oal|is|ck|ix|sser|ts|wb)ies$": "$1ie",
  ies$: "y",
  "(ar|(?:wo|[ae])l|[eo][ao])ves$": "$1f",
  "(wi|kni|(?:after|half|high|low|mid|non|night|[^\\w]|^)li)ves$": "$1fe",
  "(ss)$": "$1",
  s$: "",
};

const irregulars: Record<string, string> = {
  // Pronouns
  I: "we",
  me: "us",
  he: "they",
  she: "they",
  them: "them",
  myself: "ourselves",
  yourself: "yourselves",
  itself: "themselves",
  herself: "themselves",
  himself: "themselves",
  themself: "themselves",
  is: "are",
  was: "were",
  has: "have",
  this: "these",
  that: "those",
  my: "our",
  its: "their",
  his: "their",
  her: "their",
  thou: "you",
  // Words ending in with a consonant and `o`
  echo: "echoes",
  dingo: "dingoes",
  volcano: "volcanoes",
  tornado: "tornadoes",
  torpedo: "torpedoes",
  // Ends with `us`
  genus: "genera",
  viscus: "viscera",
  // Ends with `ma`
  stigma: "stigmata",
  stoma: "stomata",
  dogma: "dogmata",
  lemma: "lemmata",
  schema: "schemata",
  anathema: "anathemata",
  // Other irregular rules
  ox: "oxen",
  axe: "axes",
  die: "dice",
  yes: "yeses",
  foot: "feet",
  eave: "eaves",
  goose: "geese",
  tooth: "teeth",
  quiz: "quizzes",
  human: "humans",
  proof: "proofs",
  carve: "carves",
  valve: "valves",
  looey: "looies",
  thief: "thieves",
  groove: "grooves",
  pickaxe: "pickaxes",
  passerby: "passersby",
  canvas: "canvases",
};

const uncountables: Array<string | RegExp> = [
  // Singular words with no plurals.
  "adulthood",
  "advice",
  "agenda",
  "aid",
  "aircraft",
  "alcohol",
  "ammo",
  "analytics",
  "anime",
  "athletics",
  "audio",
  "bison",
  "blood",
  "bream",
  "buffalo",
  "butter",
  "carp",
  "cash",
  "chassis",
  "chess",
  "clothing",
  "cod",
  "commerce",
  "cooperation",
  "corps",
  "debris",
  "diabetes",
  "digestion",
  "elk",
  "energy",
  "equipment",
  "excretion",
  "expertise",
  "firmware",
  "flounder",
  "fun",
  "gallows",
  "garbage",
  "graffiti",
  "hardware",
  "headquarters",
  "health",
  "herpes",
  "highjinks",
  "homework",
  "housework",
  "information",
  "jeans",
  "justice",
  "kudos",
  "labour",
  "literature",
  "machinery",
  "mackerel",
  "mail",
  "media",
  "mews",
  "moose",
  "music",
  "mud",
  "manga",
  "news",
  "only",
  "personnel",
  "pike",
  "plankton",
  "pliers",
  "police",
  "pollution",
  "premises",
  "rain",
  "research",
  "rice",
  "salmon",
  "scissors",
  "series",
  "sewage",
  "shambles",
  "shrimp",
  "software",
  "staff",
  "swine",
  "tennis",
  "traffic",
  "transportation",
  "trout",
  "tuna",
  "wealth",
  "welfare",
  "whiting",
  "wildebeest",
  "wildlife",
  "you",
  /pok[eé]mon$/i,
  // Regexes.
  /[^aeiou]ese$/i, // "chinese", "japanese"
  /deer$/i, // "deer", "reindeer"
  /fish$/i, // "fish", "blowfish", "angelfish"
  /measles$/i,
  /o[iu]s$/i, // "carnivorous"
  /pox$/i, // "chickpox", "smallpox"
  /sheep$/i,
];

export { irregulars, plurals, singulars, uncountables };
